name: Deploy to EC2
run-name: Running CICD Workflow

on:
  push:
    branches:
      - main
      
env:
  AWS_REGION: ap-northeast-2
      
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout to main branch
        uses: actions/checkout@v3
        with:
          ref: main
          
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up application.yaml from GitHub Secrets
        run: |
          mkdir -p ./src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yaml

      - name: Verify application.yaml content
        run: cat ./src/main/resources/application.yaml
        
      - name: Build project
        run: ./gradlew clean build -x test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: geonoo/my-spring-boot-app:latest
          push: true
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull geonoo/my-spring-boot-app:latest
            docker stop my-spring-boot-app || true
            docker rm my-spring-boot-app || true
            docker run -d -p 8080:8080 \
                    -v /home/ubuntu/app/config/application.yaml:/app/config/application.yaml \
                    --name my-spring-boot-app geonoo/my-spring-boot-app:latest